version: '3'
services:
  nifi:
    image: mkobit/nifi
    container_name: nifi_first
    ports:
      - 8080:8080
      - 8081:8081
    environment:
      - NIFI_WEB_HTTP_PORT=8080
      - NIFI_ZK_CONNECT_STRING=zookeeper:2181
    volumes:
      - ./IN:/opt/nifi/IN
      - ./OUT:/opt/nifi/OUT
   

  zookeeper:
    hostname: zookeeper
    container_name: zookeeper_first
    image: 'bitnami/zookeeper:latest'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
